# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import CC_pb2 as CC__pb2


class CcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnReadImg = channel.unary_unary(
                '/cc_service.CcService/OnReadImg',
                request_serializer=CC__pb2.ImgRequest.SerializeToString,
                response_deserializer=CC__pb2.ImgResponse.FromString,
                )
        self.OnAnalyzedImg = channel.unary_unary(
                '/cc_service.CcService/OnAnalyzedImg',
                request_serializer=CC__pb2.CcRequest.SerializeToString,
                response_deserializer=CC__pb2.CcResponse.FromString,
                )


class CcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OnReadImg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnAnalyzedImg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnReadImg': grpc.unary_unary_rpc_method_handler(
                    servicer.OnReadImg,
                    request_deserializer=CC__pb2.ImgRequest.FromString,
                    response_serializer=CC__pb2.ImgResponse.SerializeToString,
            ),
            'OnAnalyzedImg': grpc.unary_unary_rpc_method_handler(
                    servicer.OnAnalyzedImg,
                    request_deserializer=CC__pb2.CcRequest.FromString,
                    response_serializer=CC__pb2.CcResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cc_service.CcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OnReadImg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cc_service.CcService/OnReadImg',
            CC__pb2.ImgRequest.SerializeToString,
            CC__pb2.ImgResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OnAnalyzedImg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cc_service.CcService/OnAnalyzedImg',
            CC__pb2.CcRequest.SerializeToString,
            CC__pb2.CcResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
