# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CC.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x43\x43.proto\x12\ncc_service\"Z\n\nImgRequest\x12\x0b\n\x03img\x18\x01 \x01(\x0c\x12\x32\n\x0e\x63\x61meraSettings\x18\x02 \x01(\x0b\x32\x1a.cc_service.CameraSettings\x12\x0b\n\x03msg\x18\x03 \x01(\t\"]\n\x0e\x43\x61meraSettings\x12\x10\n\x08\x63\x61meraId\x18\x01 \x01(\x03\x12\x12\n\nCameraName\x18\x02 \x01(\t\x12\x11\n\tIPAddress\x18\x03 \x01(\t\x12\x12\n\ncameraCode\x18\x04 \x01(\t\"\x1a\n\x0bImgResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\"l\n\tCcRequest\x12.\n\x0c\x63\x63\x44\x65tailList\x18\x01 \x01(\x0b\x32\x18.cc_service.ccDetailList\x12\x10\n\x08\x64\x61tetime\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61meraId\x18\x03 \x01(\x03\x12\x0b\n\x03msg\x18\x04 \x01(\t\"6\n\x0c\x63\x63\x44\x65tailList\x12&\n\x08\x63\x63\x44\x65tail\x18\x01 \x03(\x0b\x32\x14.cc_service.ccDetail\"\x84\x01\n\x08\x63\x63\x44\x65tail\x12\x0c\n\x04\x63\x63Id\x18\x01 \x01(\x03\x12\"\n\x06points\x18\x02 \x01(\x0b\x32\x12.cc_service.Points\x12\x16\n\x0eindexPointBase\x18\x03 \x01(\x05\x12.\n\x0cobjOtherInfo\x18\x04 \x01(\x0b\x32\x18.cc_service.objOtherInfo\"\xa0\x01\n\x06Points\x12\"\n\x07topLeft\x18\x01 \x01(\x0b\x32\x11.cc_service.Point\x12#\n\x08topRight\x18\x02 \x01(\x0b\x32\x11.cc_service.Point\x12&\n\x0b\x62ottomRight\x18\x03 \x01(\x0b\x32\x11.cc_service.Point\x12%\n\nbottomLeft\x18\x04 \x01(\x0b\x32\x11.cc_service.Point\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"\x0e\n\x0cobjOtherInfo\"\x19\n\nCcResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t2\x89\x01\n\tCcService\x12<\n\tOnReadImg\x12\x16.cc_service.ImgRequest\x1a\x17.cc_service.ImgResponse\x12>\n\rOnAnalyzedImg\x12\x15.cc_service.CcRequest\x1a\x16.cc_service.CcResponseB\x17\xaa\x02\x14Iroato.IroatoGRPCLibb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CC_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\024Iroato.IroatoGRPCLib'
  _globals['_IMGREQUEST']._serialized_start=24
  _globals['_IMGREQUEST']._serialized_end=114
  _globals['_CAMERASETTINGS']._serialized_start=116
  _globals['_CAMERASETTINGS']._serialized_end=209
  _globals['_IMGRESPONSE']._serialized_start=211
  _globals['_IMGRESPONSE']._serialized_end=237
  _globals['_CCREQUEST']._serialized_start=239
  _globals['_CCREQUEST']._serialized_end=347
  _globals['_CCDETAILLIST']._serialized_start=349
  _globals['_CCDETAILLIST']._serialized_end=403
  _globals['_CCDETAIL']._serialized_start=406
  _globals['_CCDETAIL']._serialized_end=538
  _globals['_POINTS']._serialized_start=541
  _globals['_POINTS']._serialized_end=701
  _globals['_POINT']._serialized_start=703
  _globals['_POINT']._serialized_end=732
  _globals['_OBJOTHERINFO']._serialized_start=492
  _globals['_OBJOTHERINFO']._serialized_end=506
  _globals['_CCRESPONSE']._serialized_start=750
  _globals['_CCRESPONSE']._serialized_end=775
  _globals['_CCSERVICE']._serialized_start=778
  _globals['_CCSERVICE']._serialized_end=915
# @@protoc_insertion_point(module_scope)
